models_config_path: 'bots/realty.yml'

llm_model_name: 'gpt-4'  # Best for production. Fast and accurate.

# llm_model_name = 'gpt-3.5-turbo'    # not good for OnboardBot
# llm_model_name = 'mistralai/mistral-medium' # not good for Onboardbot?

# very good for OnboardBot. strictest conformity to implicit field requirements.
# for example, will make the user correct "octopus" if the field name is "favorite_marine_mammal", b/c octopus is not a mammal.

# llm_model_name = 'anthropic/claude-3-opus' # great for OnboardBot. Slower than gpt-4

# llm_model_name = 'anthropic/claude-3-sonnet' # good for OnboarBot. Quick. Not 100% accurate

# good for Onboardbot! great for playing with it. good for production IF strict imlplicit field adherance
# is not required. For example, if "octopus" is a good enough answer for "favorite_marine_mammal".
# llm_model_name = 'anthropic/claude-3-haiku'
